import axiosInstance from './axios/axios';
import {
  axiosGoogleAccessToken,
  axiosKakaoAccessToken,
  axiosNaverAccessToken,
  axiosConnectSSE,
  axiosDeleteUser,
  axiosDisconnectSSE,
  axiosEditUsername,
  axiosHotBoardList,
  axiosLike,
  axiosMyPosts,
  axiosMyScraps,
  axiosPost,
  axiosPosts,
  axiosRealtimeTop10,
  axiosScrapPost,
  axiosTimeSync,
  axiosUploadImages,
  axiosUploadPost,
  axiosUserProfile,
  axiosGetAutocomplete,
  axiosSearchRealtimeBoards,
  axiosSearchRealtimePosts,
  axiosSearchFixedBoardPosts,
} from './axios/axios';

export {
  axiosInstance,
  axiosGoogleAccessToken,
  axiosKakaoAccessToken,
  axiosNaverAccessToken,
  axiosConnectSSE,
  axiosDeleteUser,
  axiosDisconnectSSE,
  axiosEditUsername,
  axiosHotBoardList,
  axiosLike,
  axiosMyPosts,
  axiosMyScraps,
  axiosPost,
  axiosPosts,
  axiosRealtimeTop10,
  axiosScrapPost,
  axiosTimeSync,
  axiosUploadImages,
  axiosUploadPost,
  axiosUserProfile,
  axiosGetAutocomplete,
  axiosSearchRealtimeBoards,
  axiosSearchRealtimePosts,
  axiosSearchFixedBoardPosts,
};
